### ISSUE TITLE
if  using c++17 will realization of more help to this library?

### ISSUE THREAD

**Issue by sgf** [marcizhu/Cereal#11]
i found another Serialization Library is looks very good.it's using C++ 17.
https://github.com/felixguendling/cista

It implements sample serialization & reflection.

The most important it's api, looks very clean and nice.

**Comment by marcizhu** [comment]
I agree with you, cista's API looks very clean, and I've seen similar API implementations in a lot of serialization libraries. Changing the API right now it's not a really good idea, because I still want to implement some features to this library and I want to retain backwards-compatibility, and changing the API will break it. Maybe at some point in the near future I will publish Cereal 2.0.0 (maybe with another name as you suggested 😜) and it will have an API similar to cista's API.

C++17 for sure makes the API look a lot cleaner, but also makes compilation a lot difficult: you see, not all the compilers support all the C++17 features yet, some are experimental still and I don't like relying on experimental stuff. For sure, once C++17 is officially supported in all major compilers I will update the code and add some really interesting C++17 features to the library.

Again, sorry for the late response :D

**Comment by sgf** [comment]
thanks for your response.
I agree with you,too.😀
